apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: task-scheduler-rollout
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-scheduler
  template:
    metadata:
      labels:
        app: task-scheduler
    spec:
      containers:
      - name: task-scheduler
        image: uweeds/task-scheduler:v2
        ports:
        - containerPort: 5000
  strategy:
    canary:
      steps:
      - setWeight: 50
      - pause: {duration: 10s}
      - setWeight: 100
      - pause: {duration: 10s}
